name: litte

on:
  push:
    paths:
      - '.github/workflows/litte.yml'
      - 'commit/**'
  schedule:
    - cron: 0 */4 * * *
  repository_dispatch:
  workflow_dispatch:
    inputs:
      packages:
        description: 'packages'
        required: false
        default: 'false'	

jobs:
  job_litte:
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    runs-on: ubuntu-latest

    name: Update litte
    strategy:
      fail-fast: false
      matrix:
        target: [master]
        
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Initialization environment
      run : |
        git config --global user.email "actions@github.com"
        git config --global user.name "action"
        sudo timedatectl set-timezone "Asia/Shanghai"
        
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x .github/diy/${{matrix.target}}.sh
        git clone -b master https://github.com/zuoweiid/backup.git ${{matrix.target}}
        
        if [ -d $GITHUB_WORKSPACE/.github/404 ]; then          ## 判断！当有 404 目录时移动至上级目录，
            mv ${{matrix.target}}/* $GITHUB_WORKSPACE/.github/404
        else
            mkdir -p $GITHUB_WORKSPACE/.github/404             ## 创建 404 目录
            
            cd $GITHUB_WORKSPACE
            mv ${{matrix.target}}/404 ./
        fi
        
        cd ${{matrix.target}}
        
        git rm -r --cache * >/dev/null 2>&1 &
        rm -rf `find ./* -maxdepth 0 -type d ! -name "commit"` >/dev/null 2>&1     
        $GITHUB_WORKSPACE/.github/diy/litte.sh
        bash /$GITHUB_WORKSPACE/.github/diy/convert_translation.sh
        bash /$GITHUB_WORKSPACE/.github/diy/create_acl_for_luci.sh -a
        bash /$GITHUB_WORKSPACE/.github/diy/Modify.sh
        
        cd $GITHUB_WORKSPACE
        mv $GITHUB_WORKSPACE/.github/404 ${{matrix.target}}            ## 移动 404 目录到 litte 目录内


    - name: Upload
      env: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        cd $GITHUB_WORKSPACE/${{matrix.target}}
        if git status --porcelain | grep .; then
          Emoji=("🌸" "🐌" "🌿" "⛅" "🍂" "💦" "💤" "💭" "🍭" "🎉" "🎁" "🎈" "🐾" "🎨" "💋" "🍓" "🍕" "🍉" "🙈" "🤡" "🍡")
          git add .
          git commit -am "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} update $(date +%Y-%m-%d" "%H:%M:%S)"
          git push --quiet "https://${{ secrets.ACCESS_TOKEN }}@github.com/kenzok8/litte.git" HEAD:master
        else
          echo "nothing to commit"
          exit 0
        fi || exit 0

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
